FROM nanolambda/base-python:3.11

COPY handler.py /function/handler.py
# If you have requirements.txt, uncomment:
# COPY requirements.txt /function/requirements.txt
# RUN pip install -r /function/requirements.txt
